### ISSUE TITLE
Faster Heading Snapping

### ISSUE THREAD

**Issue by Berdenson** [frc937/robot2024#169]
Drive team / Gabriel wants the bot to snap faster. Probably change one or both of these values below to be faster. Preferably create a new constant for that value. 
![image](https://github.com/frc937/robot2024/assets/91093973/9cc2e5bd-4049-4da2-9075-38c36ac94f16)

**Comment by Berdenson** [comment]
Flora we'd like your input on whether or not we need this.

**Comment by willitcode** [comment]
Very much super totally cannot at all change any of those values to be faster. Like, is not possible. However, I maybe found a solution to the issue—see Drive.java:171 on [heading-snapping-speed](https://github.com/frc937/robot2024/tree/heading-snapping-speed/src/main/java/frc/robot/subsystems/Drive.java#L171).

**Comment by willitcode** [comment]
This is fixed, but the problem now is that it's way too fast and that it doesn't really turn. Stay tuned for another issue trying to fix those problems.
