### ISSUE TITLE
JavaDoc all the GKC things

### ISSUE THREAD

**Issue by willitcode** [frc937/robot2024#180]
Bunch of stuff in [GKC](https://github.com/frc937/robot2024/tree/gkc-2024) needs JavaDoc. Keep in mind that commands only require JavaDoc for the classes themselves and their constructors.

- AddressableLightStrip.java:49: No description for `@param`
- AddressableLightStrip.java:50: No description for `@param`
- DriveToAmpBlue.java
- DrivetoAmpRed.java
- DriveToCenterAuto.java
- DumpNote.java
- OnePieceAutoButItWorksISwear.java
- PickUpFromCenterAuto.java
- RobotContainer.java:289: `@link` reference is misspelled
  - This is causing JavaDoc build to fail
- RobotContainer.java:275: JavaDoc public field
- RobotContainer.java:268: JavaDoc public field
- RobotContainer.java:273: JavaDoc public field
- RobotContainer.java:271: JavaDoc public field

**Comment by Berdenson** [comment]
it ain't closin now is it https://youtu.be/shlG2JsY0gU?si=gyda7T8lR56Zvxcl
