### ISSUE TITLE
Comply with Team 937 formatting

### ISSUE THREAD

**Issue by willitcode** [frc937/robot2024#2]
- Yeet Hungarian Notation
- Make subsystems `public static` (and get rid of dependency injection)
- Rename `Constants.OperatorConstants` to `Constants.Driver`

**Comment by willitcode** [comment]
Forgot to get rid of dep injection, reopening and submitting a new pr

**Comment by QuackitsQuinn** [comment]
Some small things were missed (leftover Hungarian Notation and missing access modifiers)
