### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by willitcode** [frc937/robot2024#24]
We need to decide how granular we want to go this year. I think that it's probably not that important, but I do think we should at the very least add the same test we had last year that just instantiated RobotContainer.

Mostly I just don't want to double the time our newbies are spending on their code by making them also write unit tests.

@QuackitsQuinn @Berdenson thoughts?

**Comment by Berdenson** [comment]
I think we should absolutely have a unit test for RobotContainer. Otherwise, it might be worth it since we've already had a lot of free time with projects.

**Comment by willitcode** [comment]
True. Plus, writing unit tests is a useful skill.

Then again, maybe our time would be better spent on writing the World's Best Autonomous Routine(s).
