### ISSUE TITLE
Minor cleanup

### ISSUE THREAD

**Issue by willitcode** [frc937/robot2024#26]
- Make commands private again, since if they're ever needed outside of RobotContainer, you're most likely doing something wrong
  - Is there any real reason to make them final? I don't think so
- Maybe bind a button to DeployPneumatics
  - One of these days I'm going to write a button-binding GUI for FRC
- JavaDoc the Intake instance in RobotContainer
- JavaDoc RunIntake
- Move DeployMailbox JavaDoc from the constructor to the class as a whole

**Comment by willitcode** [comment]
Include #24 in this

**Comment by Berdenson** [comment]
https://youtu.be/oY-H2WGThc8
