### ISSUE TITLE
Auto #0: Taxi

### ISSUE THREAD

**Issue by Berdenson** [frc937/robot2024#39]
A simple and basic auto to drive us out of the starting area to get us the taxi point. Look at the 2023 auto taxi code for reference. [2023 Auto Taxi Code Link](https://github.com/frc937/robot2023/blob/main/src/main/java/frc/robot/commands/StartLeavingCommunity.java)

**Comment by willitcode** [comment]
That's not the full auto code from 2023, that's just the start. There's some command groups involved in the full implementation.
