### ISSUE TITLE
JavaDoc auto drive commands

### ISSUE THREAD

**Issue by willitcode** [frc937/robot2024#60]
What it says on the tin. Make sure you document what the params for the constructor are as well.

I think maybe we should require JavaDoc for command constructors as well as the command classes.

**Comment by willitcode** [comment]
@QuackitsQuinn @Berdenson thoughts on javadoc for command constructors?

**Comment by QuackitsQuinn** [comment]
I think it's a good idea to add Javadoc for command constructions because it shows the usage of the command and could include stuff like simple examples that could be used as references. Too much documentation never hurt anyone*

*as far as I know

**Comment by willitcode** [comment]
Agreed, though I think we shouldn't require more than "Creates a new (classname)" and `@param`s, since the `@param`s are the only part you *need* to be able to use the method.

**Comment by Berdenson** [comment]
I say yes
