### ISSUE TITLE
Add javadoc

### ISSUE THREAD

**Issue by Berdenson** [frc937/robot2024#73]
AimWithLimelight, DriveAutoFieldOriented, and DriveAutoRobotOriented, don't have javadoc for the class.

**Comment by QuackitsQuinn** [comment]
"Your stupid, heres why" - Ara

DriveAutoFieldOriented and DriveAutoRobotOriented already have an issue that is almost ready to merge.

**Comment by Berdenson** [comment]
Also while you're at it can you please fix the javadoc for the DriveFieldOrientedHeadingSnapping constructor. It lists the Y axis twice and is mildly confusing.
