### ISSUE TITLE
Move controllers to their own file

### ISSUE THREAD

**Issue by QuackitsQuinn** [frc937/robot2024#95]
I figured I'd put this here because it might be a good idea. I have realized that it might just be 100% easier to just make a class dedicated to dealing with the controllers. 

It would completely remove the weirdness of doing them in RobotContainer, and would create a specific place for controllers and keybinds to go.

**Comment by willitcode** [comment]
Could work? I don't remember exactly how WPILib controller bindings work. I thiiiiiiink if you call the a(), b(), etc. methods from anywhere, it binds those to the CommandScheduler EventLoop... but I'm not sure. Would require some testing.

**Comment by QuackitsQuinn** [comment]
I did some looking at the code for `CommandXboxController` and by default it grabs the default button loop from the command scheduler, so I think it will be fine.

**Comment by willitcode** [comment]
Cool, have fun
